### ISSUE TITLE
Images?

### ISSUE THREAD

**Issue by anitagraham** [rails-front-end/external_asset_pipeline#106]
I couldn't see any documentation on how to deal with images processed by `webpack.`

As far as I could see all your examples only use images as background, not as an `<img src='what?' />` element.

Any clues - or write my own helper?

**Comment by anitagraham** [comment]
Closing. I wasn't using the path to the images. Sorry.

**Comment by rmacklin** [comment]
Hi @anitagraham! So have you figured out your issue? If so, I'll close the issue. If not, can you share the code so I can look into it?

**Comment by rmacklin** [comment]
I'll close this but let me know if you are having an issue.
